version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:18.17

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm ci
      - run: npm run build:lib
      # - run:
      #       name: Run tests
      #       command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      # devployment lib
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: cd dist/ng-simple-sidebar; npm publish --userconfig ../../.npmrc
  docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      # deployment docs
      - run:
          name: Configure dependencies
          command: |
            git config user.email "$GIT_EMAIL"
            git config user.name "ci-build"
            ssh git@github.com -oStrictHostKeyChecking=no || true
      - run:
          name: Build Showcase Application
          command: npm run build:showcase
      - run:
          name: Deploy docs to gh-pages branch
          command: npm run gh-pages

workflows:
  version: 2
  lib-build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - docs:
          requires:
            - build
          filters:
            branches:
              only:
                - master
