import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/router';
import 'rxjs';
import 'skeleton-css/css/normalize.css';
import 'skeleton-css/css/skeleton.css';
import 'font-awesome/css/font-awesome.min.css';
